name: MainMenuPlugin
version: '${project.version}'
main: com.maks.mainmenuplugin.MainMenuPlugin
api-version: '1.20'
commands:
  suicide:
    description: Kill yourself in-game.
    usage: /suicide
  menu:
    description: Opens the custom main menu.
    usage: /menu
softdepend: [PlayerDataPlugin]
