name: MainMenuPlugin
version: '1.0-SNAPSHOT'
main: com.maks.mainmenuplugin.MainMenuPlugin
api-version: '1.20'
commands:
  suicide:
    description: Kill yourself in-game.
    usage: /suicide
  menu:
    description: Otwiera niestandardowe menu